### ISSUE TITLE
Ipv6 is long address, Command lsof  can't display  port to the log address

### ISSUE THREAD

**Issue by zhrf2020** [lsof-org/lsof#102]
Repetition scenario：
1  Add ipv6
ip -6 addr add abcd:ef10:ffff:ffff:ffff:ffff:ffff:ff62 dev enp1s0
ip -6 addr add abcd:ef10::ff62 dev enp1s0   
 
2  The test code （python2.7）
code1:
#vim test_log.py
import socket,sys,time 
tcpT6Server=socket.socket(socket.AF_INET6,socket.SOCK_STREAM)
tcpT6Server.bind(("abcd:ef10:ffff:ffff:ffff:ffff:ffff:ff62",8888))
tcpT6Server.listen(5)
time.sleep(10000)

code2: 
#vim test.py
import socket,sys,time 
tcpT6Server=socket.socket(socket.AF_INET6,socket.SOCK_STREAM)
tcpT6Server.bind(("abcd:ef10::ff62",8888))
tcpT6Server.listen(5)
time.sleep(10000)

3 Run  codes 
#python  test_log.py
#python  test.py

4 Execution port command
#lsof -i:8888
#netstat -anpW | grep 8888

5  Results
Command lsof can't display ipv6 address (abcd:ef10:ffff:ffff:ffff:ffff:ffff:ff62) port number 8888

6   Code snippet
 * Assemble four uint32_t's from 4 X 8 hex digits into s6_addr32[].
 */
	for (i = 0, len = strlen(as);
	     (i < 4) && (len >= 8);
	     as += 8, i++, len -= 8)
	{
	    (void) strncpy(buf, as, 8);
	    buf[8] = '\0';
	    ep = (char *)NULL;
	    if ((ad->s6_addr32[i] = (uint32_t)strtoul(buf, &ep, 16))
	    ==  (uint32_t)UINT32_MAX || !ep || *ep)
		break;
	}
	return((*as || (i != 4) || len) ? 1 : 0);
}
#endif	/* defined(HASIPv6) */

There seems to be wrong ：
            if ((ad->s6_addr32[i] = (uint32_t)strtoul(buf, &ep, 16))
	     ==  (uint32_t)UINT32_MAX || !ep || *ep)

Correct code:
           if (   (ad->s6_addr32[i] = (uint32_t)strtoul(buf, &ep, 16))
	     == ((uint32_t)UINT32_MAX || !ep || *ep)   )

**Comment by masatake** [comment]
Why don't you make a pull request for this?
I expect this well written comment is reused in your commit log.

**Comment by masatake** [comment]
I forgot to write an important message that should come first: "Thank you for reporting."

**Comment by masatake** [comment]
Reproduced even with lo instead of lo.
nc can be used instead of the pyhon scripts.

```
# ip -6 addr add abcd:ef10:ffff:ffff:ffff:ffff:ffff:ff62 dev lo
# nc -6 -l  abcd:ef10:ffff:ffff:ffff:ffff:ffff:ff62 8888 &
[1] 6762
# ./lsof -p 6762 -a -d fd -P -n
COMMAND  PID   USER   FD   TYPE DEVICE SIZE/OFF    NODE NAME
nc      6762 yamato    0u   CHR  136,6      0t0       9 /dev/pts/6
nc      6762 yamato    1u   CHR  136,6      0t0       9 /dev/pts/6
nc      6762 yamato    2u   CHR  136,6      0t0       9 /dev/pts/6
nc      6762 yamato    3u  sock    0,9      0t0 5833594 protocol: TCPv6
```

The last line should be
```
nc      6762 yamato    3u  IPv6 5833594      0t0  TCP [abcd:ef10:ffff:ffff:ffff:ffff:ffff:ff62]:8888 (LISTEN)
```

**Comment by zhrf2020** [comment]
@masatake   Sorry for the late reply. I quite agree with your repair method.

**Comment by zhrf2020** [comment]
The fix for this problem can be found at the following addresshttps://github.com/masatake/lsof/commit/6ff269c8e8dd50e30be236a7f353aedb28d0246d
