### ISSUE TITLE
Behaviour of offset field on -F inconsistent with the man page

### ISSUE THREAD

**Issue by JustAnotherArchivist** [lsof-org/lsof#118]
Using lsof 4.91 and 4.93.2 at least (Debian stable and sid), the offset field for `-F` does not work according to the man page documentation (or my understanding of it).

When `FILE` is opened by exactly one process, I'd expect `lsof -Fo FILE` to produce three lines similar to:

```
p676080
f4
o49152
```

Instead, it only prints the first two lines, i.e. the offset is omitted. When `-F` isn't used, the offset has to be enabled explicitly with `-o` (at least for regular files). This works, but the output is:

```
p676080
f4
o0t49152
```

The `0t` prefix is used on the normal output (i.e. without `-F`) to distinguish between decimal and hexadecimal notation. But the `o` field on `-F` is always decimal, so I'd expect it to not include that prefix. This would match the `s` field, which is also defined to be decimal and does not include the prefix. Also, the man page explicitly mentions the `0x` prefix for the hexadecimal fields (e.g. `D`, `F`, `r`) but does not include `0t` for `o`.

So the two changes I'd suggest are enabling `-o` when the `-F` list includes `o` and removing the `0t` prefix from the field in that output mode.

**Comment by masatake** [comment]
```
p676080
f4
o49152
```
This one is reproduced.

```
p676080
f4
o0t49152
```
Could you tell me the way to reproduce this?
I expect an actual command line.

**Comment by JustAnotherArchivist** [comment]
`lsof -Fo -o FILE` produces the line starting with `o0t` (or `o0x` for larger offsets).

**Comment by masatake** [comment]
Reproduced. Thank you. I'll inspect the way to fix these.

**Comment by masatake** [comment]
You reported two issues.
1. -Fo doesn't work (in many fds)
2.  0t in -Fo output should not used because it is always 0t.

Locally, I found the way to fix 1. 1. is a bug report.

I found what you wrote in 2. is incorrect.
With -o `n` option, 0x is used as the replacement of 0t.  The bug of 1. makes you see 0t always.

So, I will make a pull request for fixing 1.
```
[yamato@control lsof]$ sudo ./lsof -Fo | grep ^o | sort | uniq -c | head
sudo ./lsof -Fo | grep ^o | sort | uniq -c | head
lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1000/gvfs
      Output information may be incomplete.
  91476 o0t0
     89 o0t101
     86 o0t103
     86 o0t1082168
      2 o0t118784
     86 o0t11993088
      1 o0t1205
      1 o0t1214
      4 o0t126341
      8 o0t13101432
[yamato@control lsof]$ sudo ./lsof -Fo -o1 | grep ^o | sort | uniq -c | head
sudo ./lsof -Fo -o1 | grep ^o | sort | uniq -c | head
lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1000/gvfs
      Output information may be incomplete.
  91329 o0t0
      3 o0t2
     18 o0t4
     25 o0t5
    345 o0x1000
     94 o0x10000
     86 o0x1038
     86 o0x108338
     27 o0x1097
      4 o0x10f400000
```

**Comment by masatake** [comment]
lsof(1) says:
```
       SIZE, SIZE/OFF, or OFFSET
                  is the size of the file or the file offset in bytes.   A  value  is  dis‐
                  played  in  this  column only if it is available.  Lsof displays whatever
                  value - size or offset - is appropriate for the type of the file and  the
                  version of lsof.

...
                  The  file  size is displayed in decimal; the offset is normally displayed
                  in decimal with a leading ``0t'' if it contains  8  digits  or  less;  in
                  hexadecimal  with  a leading ``0x'' if it is longer than 8 digits.  (Con‐
                  sult the -o o option description for information on when 8 might  default
                  to some other value.)
```

**Comment by masatake** [comment]
See #119.

**Comment by masatake** [comment]
Just a question. Do you use GNU/Linux for running lsof?

**Comment by JustAnotherArchivist** [comment]
It would definitely be easier for other programs to handle the output if it were just `o` followed by a decimal number. But yeah, I can send a PR for the man page.

Yes, Debian to be specific.

**Comment by masatake** [comment]
> But yeah, I can send a PR for the man page.

Thank you.
