### ISSUE TITLE
lsof returns 1 for both no-data and error case

### ISSUE THREAD

**Issue by aabawer** [lsof-org/lsof#128]
lsof return code is non-distinctive in case of error and no processes information.
This is also documented on command's manual.

It's impossible to tell programmatically if something went wrong, or just that lsof didn't find any information. 
It makes sense to keep rc=0 when no information was found.

For example, when stating a non-existing path:

$ lsof /tmp/1
lsof: status error on /tmp/1: No such file or directory
lsof 4.91
...
$ echo $?
1

When path exists, but no information:

$ touch /tmp/1
$ lsof /tmp/1
$ echo $?
1

**Comment by masatake** [comment]
Thank you for reporting. I inspected the internal of lsof, and I found "no information" cases are handled separately in the source code level.

main.c:
```c
int main (...)
{
...
    rv = 0;

/*
 * See if all requested information was displayed.  Return zero if it
 * was; one, if not.  If -V was specified, report what was not displayed.
 */
    for (str = Cmdl; str; str = str->next) {
            /* conditions ... */
	    rv = 1;
	}
     ... /* other conditions setting rv = 1 */

    return rv;
}
...
```

Let's keep the rc for the cases of "no information"  1.

Instead do rc=2 when an error occurs.

The behavior I proposed here is the same as grep. 
Quoted from the man page of grep:
```
EXIT STATUS
       Normally the exit status is 0 if a line is selected, 1 if no lines were
       selected, and 2 if an error occurred.  However, if the -q or --quiet or
       --silent is used and a line is selected, the exit status is 0  even  if
       an error occurred.
```

**Comment by masatake** [comment]
These descriptions must be updated.

https://github.com/lsof-org/lsof/blob/811dc78cc6404cb39d82bf01728cfdf38f097af1/00QUICKSTART#L739
https://github.com/lsof-org/lsof/blob/811dc78cc6404cb39d82bf01728cfdf38f097af1/00QUICKSTART#L170

**Comment by aabawer** [comment]
IMHO, its more straightforward to stick to the default shell commands behavior of rc=0 when no errors occur; no-information is expected when you have path which is currently unoccupied by some processes, so it seems legit to me to return 0 in this case and non-zero rc in a case of an error.

**Comment by masatake** [comment]
I want to keep the behavior of lsof as written in  "16. The Lsof Exit Code and Shell Scripts" of 00QUICKSTART file.
```
16. The Lsof Exit Code and Shell Scripts
========================================

  When lsof exits successfully it returns an exit code based on
  the result of its search for specified files.  (If no files were
  specified, then the successful exit code is 0 (zero).)

  If lsof was asked to search for specific files, including any
  files on specified file systems, it returns an exit code of 0
  (zero) if it found all the specified files and at least one file
  on each specified file system.  Otherwise it returns a 1 (one).

  If lsof detects an error and makes an unsuccessful exit, it
  returns an exit code of 1 (one).

  You can use the exit code in a shell script to search for files
  on a file system and take action based on the result -- e.g.,

    #!/bin/sh
    lsof <file_system_name> > /dev/null 2>&1
    if test $? -eq 0
    then
      echo "<file_system_name> has some users."
    else
      echo "<file_system_name> may have no users."
    fi
```

On the other hand, I understand lsof should provide a way to distinguish two results: no-data and error case.

lsof will provide the way. So you can do
```
mylsof()
{
    lsof "$@"
    case $? in
    0|1) return 0;;
    *)    return 1;;
    esac
}
```

I don't want to receive another issue: "lsof returns 0 for both no-data and success case."

**Comment by masatake** [comment]
@[aabawer](https://github.com/aabawer), I'm sorry to take a long time for fixing this.
In #129, we introduced -Q option that may solve this issue.
