### ISSUE TITLE
Making new release 4.95.0

### ISSUE THREAD

**Issue by masatake** [lsof-org/lsof#135]
Should be merged:
- [x] #156 
- [x] #129 
- [x] ...

Should be fixed:
- [x] #169 
- [x] ...

**Comment by masatake** [comment]
In two weeks, I would like to make a new release.
I would like to merge https://github.com/lsof-org/lsof/pull/129.
However, it requires updating our documents.
Can I ask you to review the changes to the documents?

**Comment by dilinger** [comment]
Hi, just a ping to make sure this is still going to happen (and that you're not waiting on anything from me).

**Comment by masatake** [comment]
Sorry to be late. It has being going to happen in my mind. However, I cannot find the time. I will find it by the end of this year.

**Comment by masatake** [comment]
Though we have not fixed some issues targeting 4.95.0 and merged pull requests targeting 4.95.0, I would like to release a new version. It seems that there are some important pull requests for FreeBSD. So feel free to plan 4.96.0.

**Comment by masatake** [comment]
@dilinger, thank you. Without you, I couldn't make the release.
I invited you to this team. Could you consider joining this team to maintain lsof?
If you accept the invitation, please continue to read...

Within the linux dialect topics and dialect neutral topics, I would like you to do as you want (if you are interested in driving the development of lsof, of course).

The only rule is that if you want to change the code, it must be proposed via pull request.
About a tiny change, you can merge the pull request as soon as the test running on the CI/CD environment at cicleci reports "passed".

About the middle size change, assign me as a reviewer, and give me a fortnight. I will try to find the time for reviewing.
I also do the same to you when I make a middle size change.
