### ISSUE TITLE
/usr/ports/sysutils/lsof does not build on FreeBSD-13.0 (released 2021-04-13)

### ISSUE THREAD

**Issue by joeinwap** [lsof-org/lsof#154]
FreeBSD-13.0 (which was released 12 days ago) has legacy lsof-4.93.2 instead of the GitHub version.

```
ld: error: undefined symbol: FILEDESC_KVM_LOAD_PWD
>>> referenced by dproc.c
>>>                        dproc.o:(gather_proc_info)
cc: error: linker command failed with exit code 1
make[1]: stopped in /usr/ports/sysutils/lsof/work/lsof-4.93.2
Report the failure to the maintainer.

```
![VirtualBox_FreeBSD-13_25_04_2021_04_03_42](https://user-images.githubusercontent.com/8685164/115991525-b587c100-a57d-11eb-823e-27d004dbc6f4.png)

**Comment by bzoop** [comment]
Additionally, lsof's zfs support [doesn't seem to be working](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=253553) (FreeBSD 13 is now based on openzfs).

**Comment by joeinwap** [comment]
Fixed within a week after report with version 4.94.0.
