### ISSUE TITLE
[darwin] dialect maintenance volunteer

### ISSUE THREAD

**Issue by dannykansas** [lsof-org/lsof#157]
I noticed that tests are not complete for `darwin`; I'm opening this issue per the README instructions for volunteering maintenance of a given dialect. 

I'd also like to widen the tests, if necessary, for `darwin`.

**Comment by masatake** [comment]
I sent an invitation to you.
Through merging #156, I will show what I did as a maintainer.

**Comment by dannykansas** [comment]
Great, got the invite. I’ll read through that and get a PR together

**Comment by masatake** [comment]
It seems that this issue is solved.
