### ISSUE TITLE
warning message not supressed in AIX

### ISSUE THREAD

**Issue by sanumesh** [lsof-org/lsof#187]
Hello

In AIX, we still see the warning message related to Kernel ID check in spite of using the -w option

WARNING: compiled for AIX version 6.1.0.0; this is 7.2.0.0.

Solution :
In dialects/aix/dproc.c
Function : void ckkv(d, er, ev, ea)

The if (Fwarn) check is missing for AIX levels above 5.0.0.0

 if	AIXV<5000
...
	if (Fwarn)
	    return;
 else
...
endif

**Comment by masatake** [comment]
A pull request for the solution is welcome.

**Comment by masatake** [comment]
@sanumesh 
> Solution :
...

A pull request is welcome.
