### ISSUE TITLE
[linux] looking for new maintainer 

### ISSUE THREAD

**Issue by masatake** [lsof-org/lsof#192]
I would like to step down from the maintainer of the Linux dialect because I would like to focus on [lsfd](https://github.com/util-linux/util-linux/blob/master/misc-utils/lsfd.1.adoc). If you are interested in the role, please introduce yourself here.

When lsfd becomes mature enough and we cannot find a new maintainer for the dialect, I will delete the dialect from our repository as the last work as the maintainer. 

"mature" means *I*, not you, can use lsfd as the replacement of lsof.
My TODO list of lsfd can be found in https://github.com/util-linux/util-linux/pull/1418#issue-975990965 .

**Comment by masatake** [comment]
Thank you for the offer.

About Linux, we have a head maintainer of this dialect: @[dilinger](https://github.com/dilinger) and @dilinger is active. So, please cooperate with @dilinger. @dilinger, do you have any additional comments?

About darwin, there is no active maintainer of this dialect. So you will be the head maintainer of the dialect. (@dannykansas was. However, he has been absent.) I don't know darwin. So I have no helpful comment.

I wrote the rules for maintaining: https://github.com/lsof-org/lsof/blob/master/HOW_TO_MAINTAIN.rst.

I wrote the way to release a new version: https://github.com/lsof-org/lsof/blob/master/HOW_TO_RELEASE.rst.

Could you show me you are a good developer?
The first task is making a pull request implementing your comment https://github.com/lsof-org/lsof/pull/221#issuecomment-1183242582 ?
The change is small, but I would like you to write a good commit log satisfying the rules in https://github.com/lsof-org/lsof/blob/master/HOW_TO_MAINTAIN.rst.
I will review your pull request and merge it.

The second task that should be done after the first task is adding your name to https://github.com/lsof-org/lsof/blob/master/HOW_TO_MAINTAIN.rst. After receiving a pull request for the second task, I will send you the invitation to join the organization.
You will merge the pull request for the second task by yourself!


I'm still here till someone like you takes over the maintainership of the while this project.
Writing this kind of message to new volunteers is the primary task of the project maintainer:)

**Comment by jiegec** [comment]
Sure.

**Comment by masatake** [comment]
We got a great maintainer for the linux dialect.
lsfd becomes better.
After adding socket-related code to lsfd, I will remove my name from HOW_TO_MAINTAIN.rst.
