### ISSUE TITLE
build broken after #194

### ISSUE THREAD

**Issue by algorythmic** [lsof-org/lsof#197]
After 9c70ac9, the generated `lib/Makefile` ends up with:

```Makefile
AR=     ar cr ${LIB} ${OBJ}
RANLIB= ranlib ${LIB}
# ...
${LIB}: ${OBJ}
        ${AR} cr ${LIB} ${OBJ}
        ${RANLIB} ${LIB}
```

So the build fails with an error like:
```
ar cr liblsof.a ckkv.o cvfs.o dvch.o fino.o isfn.o lkud.o pdvn.o prfp.o ptti.o rdev.o regex.o rmnt.o rnam.o rnch.o rnmh.o snpf.o cr liblsof.a ckkv.o cvfs.o dvch.o fino.o isfn.o lkud.o pdvn.o prfp.o ptti.o rdev.o regex.o rmnt.o rnam.o rnch.o rnmh.o snpf.o
ar: cr: No such file or directory
make[1]: *** [liblsof.a] Error 1
make: *** [lib/liblsof.a] Error 2
```

since the `cr ${LIB} ${OBJ}` arguments end up duplicated.

**Comment by masatake** [comment]
@ffontaine, could you fix this? or should I revert your change?

**Comment by masatake** [comment]
I wonder why I could not find this brokenness when merging #194.

**Comment by masatake** [comment]
#183 doesn't work at all.

**Comment by ffontaine** [comment]
My bad, we were overriding AR in buildroot.
You can revert the commit. 
I'll update buildroot to set `LSOF_AR` and `LSOF_CC`
