### ISSUE TITLE
what licneses are lsof issued under?

### ISSUE THREAD

**Issue by system-thoughts** [lsof-org/lsof#200]
Hi, I checked the code repository and did not find any LICENSE or COPYING file.
So, what licenses are lsof issued under?

**Comment by masatake** [comment]
See the FAQ file, https://github.com/lsof-org/lsof/blob/83af0117e5a8e5a62a5712d264e4a91d3661dce9/00FAQ#L798

**Comment by system-thoughts** [comment]
Thanks for your reply, I see Centos package lsof under License:  **zlib and Sendmail and LGPLv2+**
https://git.centos.org/rpms/lsof/blob/c7/f/SPECS/lsof.spec

It is confusing, I do not see any such License / COPYING under this repository

**Comment by masatake** [comment]
Talking to the package maintainers may be better.
