### ISSUE TITLE
lsof on NetBSD, pkgsrc

### ISSUE THREAD

**Issue by tnn2** [lsof-org/lsof#219]
In NetBSD pkgsrc we maintain sysutils/lsof based on Vic's version 4.91.
The other day I [implemented](https://github.com/NetBSD/pkgsrc/blob/trunk/sysutils/lsof/files/rnmt.c) support for the upcoming NetBSD 10 red-black tree based kernel namecache on the 4.91 version. Is this projected interested in merging our patches? I could help with the maintainership.
Thought I'd ask here before I start to port things over to your codebase.

**Comment by masatake** [comment]
If you become the maintainer of the NetBSD dialect, you can merge your change.
Are you interested in maintaining it?

**Comment by masatake** [comment]
See #220. I took my best.

**Comment by masatake** [comment]
@tnn2, do I have to take any action about this topic?

**Comment by tnn2** [comment]
Hi! Sorry, was on vacation for the past 2 weeks. I did read #220 and it looks good. I'll close this issue for now and create PRs for NetBSD build fixes, starting with the more trivial ones.
