### ISSUE TITLE
lsof -i caused cpu usage 100% and blocked for a long time

### ISSUE THREAD

**Issue by shentupenghui** [lsof-org/lsof#222]
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/25290236/173520137-232e99f2-0117-4f72-8388-ad96a0e4e70b.png">
how i use lsof: 
<img width="1608" alt="image" src="https://user-images.githubusercontent.com/25290236/173520371-77c00835-8c8f-49db-9da3-36fda5c085de.png">
i've tried to use `strace` to dig out, but no useful information, can anyone help

**Comment by masatake** [comment]
If strace prints nothing, the CPU executes the application code.
If gdb is available on the system, pstack command gives us hints:

```
# pstack $(pidof lsof)
```

If strace prints something, `strace -k -p $(pidof lsof)` give us hints.

How long does lsof takes time if you don't specify `-i:354`?
```
# time lsof > /dev/null
```

I would like to know the first column of
```
cat /proc/sys/fs/file-nr
```

If too many files are opened, lsof may take long time.

**Comment by shentupenghui** [comment]
Thx to reply, here are more info:
### `pstack`
<img width="1569" alt="image" src="https://user-images.githubusercontent.com/25290236/173712393-41926aca-5496-470a-9d32-042398d201f7.png">
### `strace`
strace prints a lot of bad file descriptor like:
<img width="487" alt="image" src="https://user-images.githubusercontent.com/25290236/173712484-27743300-0dac-445f-ba19-24b21f1eb9c8.png">
### `cat /proc/sys/fs/file-nr`
<img width="1321" alt="image" src="https://user-images.githubusercontent.com/25290236/173712555-01eddf07-9d87-4673-8e72-768de3c760ec.png">
### time
running time is not fixed，takes 1~5min

**Comment by BenBE** [comment]
Can you please post the information as text instead of images?

Which OS/distro are you running on? Which version of lsof are you running (+ which of its dialects)?

**Comment by masatake** [comment]
Could you try to run lsof with limiting the number of openable file descriptors per process like: `(ulimit -n 512; lsof -i:354)` ?


Which version of linux kernel do you use?
Which version of lsof do you use?

If you run the lsof (>= 4.95.0 ) on linux (>= 5.9), lsof should not call close(2) repeatedly.
Instead, it should call close_range(2). See https://github.com/lsof-org/lsof/commit/517ee5542a80f0d70ab45ffc8d9b1e56b18b30c0

If you are using older lsof and/or older linux, the ulimit trick may help you.

**Comment by shentupenghui** [comment]
@BenBE sorry, it happened in co. 's production env which network is physically isolated ,so i cant copy any text out of there;

`uname -a`  prints:
Linux bms 4.19.90-17.ky10.x86_64 SMP GNU/Linux

@masatake 
kernel: 4.19
lsof -v: 4.93.2

ulimit -n 512  prints nothing..TT

**Comment by shentupenghui** [comment]
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/25290236/173767877-55b77dfc-a5cd-4b2d-adec-ff69d25440fc.png">

**Comment by masatake** [comment]
What is "T T"?

I'm confused.

You wrote:

```
i've tried to use `strace` to dig out, but no useful information, can anyone help 
```

However, in https://github.com/lsof-org/lsof/issues/222#issuecomment-1155855886, we saw too many close() system calls. It is useful information.


My guessing was that calling close() so many times was the bottleneck.
If my guessing was true, `ulimit -n 512` should remove the bottleneck
because the number (512) limits the number of calling close().

If the execution of lsof still takes a too long time, my guessing was wrong.


> time
> running time is not fixed， takes 1~5min

I'm not sure "taking 1~5min" is "a long time".
lsof scans all file descriptors and memory mappings of all the processes on the target system. So taking a long time can happen depending on the state of the target system.

What happens if you limit the process that lsof scans?
`time lsof -p 1 > /dev/null` makes lsof scan only PID 1.

On my this NOTE PC:
```
$ time lsof -p 1 > /dev/null
lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1001/gvfs
      Output information may be incomplete.
lsof: WARNING: can't stat() fuse.portal file system /run/user/1001/doc
      Output information may be incomplete.
lsof: WARNING: can't stat() vfat file system /run/media/usako/41D2-0E36
      Output information may be incomplete.

real    0m0.031s
user    0m0.008s
sys     0m0.009s
```

If `lsof -p 1` takes a much longer time, it implies a bottleneck is at the early stage of the execution.

**Comment by masatake** [comment]
If the bottleneck is not at the early stage, I want to see the output of:

```
# strace -c lsof -i:354
```

**Comment by shentupenghui** [comment]
'T T' like a crying face..just a meme, not important..
thanks to reply, here are more infos 
> we saw too many close() system calls. It is useful information

⬆️on my cluster, every node seem to have this problem when run `lsof -i`,  that I thought it was normal

> lsof scans all file descriptors and memory mappings of all the processes on the target system. So taking a long time can happen depending on the state of the target system.

⬆️you means the size of mem would influence `lsof` performance? 

 I use  node has 128 CPU with mem:
```
[sysop@bms-ca34-0002 ~]# cat /proc/meminfo
MemTotal:        1043823788  kB
MemFree:         1005312196   kB
MemAvailable:  1020043092 kB
```

`time lsof -p 1 > /dev/null ` seems it  take much more time than your PC

```
[sysop@bms-ca34-0002 ~]# time lsof -p 1 > /dev/null
real    0m0.572s
user   0m0.149s
sys     0m0.536s
``
below is ` strace -c lsof -i:354`, sorry I cant copy text info from prod

<img width="918" alt="image" src="https://user-images.githubusercontent.com/25290236/173971211-6835916e-219e-4526-a1dc-ab888b113f99.png">

**Comment by shentupenghui** [comment]
why there are over 65533 error on `close()`

**Comment by shentupenghui** [comment]
> lsof tries to close all fds lsof opens at the early stage of execution. On my note PC, both lsof and Linux kernel are newer than you are using, lsof can use close_range system call instead of calling close repeatedly.
 
thanks a lot,  i have solved this problem by running lsof after manually setting `ulimit` with a smaller number.

seems a kernel updating is better

**Comment by shentupenghui** [comment]
yes, but that day i misunderstand your meaning..i thought you meant first run `ulimit -n` to see my ulimit setting, and then run `lsof -i:354`

today i just do what you said, run `ulimit -n 512; lsof -i:354` together,  and works well : )

**Comment by masatake** [comment]
Oh, I see. Thank you.
