### ISSUE TITLE
[BUG] Confusing versioning?

### ISSUE THREAD

**Issue by thesamesam** [lsof-org/lsof#258]
The recent -freebsd tags are a bit confusing for distributions. They contain the implicit declarations fix (https://github.com/lsof-org/lsof/commit/52f2c48790ced81aeef98807363ec94a867bbd88) which is important for all platforms.

I see most of the other commits (if not all) are FreeBSD specific, but usually projects just mention in the release notes that the only important parts are for $X platform, so others need not stress about upgrading.

Changing the version scheme entirely I think is a bit confusing. Could you consider using point releases like before?

**Comment by lrosenman** [comment]
I'm not sure about it.  I was following @masatake 's lead. 

I'm more than happy to drop the -freebsd, but I'd like someone from the Linux (and other) dialects to weigh in.

**Comment by jiegec** [comment]
I think we can create a tag on the same commit without the suffix.

**Comment by lrosenman** [comment]
I was also just trying to *NOT* exceed my authority of FreeBSD maintainer/owner

**Comment by lrosenman** [comment]
Also feel free to add a 4.96.4 with the latest commit, I just didn't want yet another release today for a "minor" fix.

**Comment by jiegec** [comment]
I have pushed tags without the `-freebsd` suffix and we can just stay on 4.96.3.

**Comment by thesamesam** [comment]
Thanks folks! Totally understandable. It's no bother to me if there's platform-specific releases, just flag it up in the notes where applicable.

**Comment by masatake** [comment]
I decided to step down from the project maintainer ago. I have not taken any time for lsof for months. It is very nice that dialect maintainers determine their way of development and release with discussion. Please, discard my decision and design about the development and release process. I found the word in my dictionary: council system.

I have not been good enough at English. So I could not take such an approach, discussion-based dialect-unified release. Instead, I designed the dialect maintainers can run the release process asynchronously. When reading the comments about the way to release in this thread, I found this is an excellent time to talk about stepping down more explicitly.

The following items are my last requests for dialect maintainers:
- update 00CREDITS whenever receiving a contribution,
- update 00DIST whenever receiving a USER-VISIBLE contribution,
- read HOW_TO_MAINTAIN.rst and change it as you want,
- read HOW_TO_RELEASE.rst and update it, and
- rewrite the code with C99:-P.

I had seen not a few projects lose vitality when their project maintainers retired, became busy with other things, lost interest in the software, got into an accident, or got in private trouble.
lsof entered such a situation when Vic Abell retired.
lsof was so important for me. So I tried extending the life of lsof.

Hacking and releasing lsof are tasks of the maintainers. But not that's all. Finding and bringing candidates for a new maintainer is also an important task for extending the life of lsof. The HOW_TO_... may not be important for you. However, I think they are essential for the candidates to study how to work on the project.

When I find time, I will take action to step down.
Thank you for reading.

**Comment by masatake** [comment]
I removed myself from this organization after I made @jiegec one of the owners of this organization. As a developer, I will continue my research about "listing file descriptors" at https://github.com/util-linux/util-linux/blob/master/misc-utils/lsfd.c. Of course, you can call me anytime you want with `@masatake`.

@lrosenman, @jiegec Good luck!
Thank you.
