### ISSUE TITLE
[FEATURE] Build system rewrite in autotools or meson

### ISSUE THREAD

**Issue by thesamesam** [lsof-org/lsof#267]
**Is your feature request related to a problem? Please describe.**

lsof's current `Configure` script is handwritten and causes problems for cross-compilation for example as it tries to build-and-execute binaries to determine properties of the system.

This requires awkward patching and workarounds downstream in e.g. Gentoo.

**Describe the solution you'd like**

A rewrite of the build system to either autotools or meson, both of which would solve this problem and are standard in the community.

**Describe alternatives you've considered**

The configure script could develop additional options to allow overrides for e.g. cross-compile, but this wouldn't solve all the issues (see below).

**Additional context**

Various cross bugs which are awkward to handle/patch correctly:
- https://bugs.gentoo.org/432120
- https://bugs.gentoo.org/546636

The handwritten configure script often doesn't conform to modern standards:
- https://github.com/lsof-org/lsof/pull/265
- https://github.com/lsof-org/lsof/pull/248

**Comment by thesamesam** [comment]
@jiegec @lrosenman if you're fine with this in principle, we (Gentoo) are happy to work on this and provide a PR, but didn't want to waste effort on it if it would be rejected. Let us know what you think, thanks!

**Comment by lrosenman** [comment]
I'm fine with it.  Can you investigate what changes would also be needed for the FreeBSD sysutils/lsof port for whatever you do?

**Comment by SoapGentoo** [comment]
Given that the Autotools are UNIX-agnostic, I don't see any major hurdles for the FreeBSD port. Do you prefer Meson or Autotools? Here's a few points to consider:

1. Autotools is acceptable for FreeBSD for base system packages, whereas Meson isn't (due to it being written in python)
2. Autotools generally only requires POSIX tools (sed, awk, sh, a C compiler), whereas Meson requires python and ninja.

**Comment by lrosenman** [comment]
FreeBSD ports supports autotools natively with the framework.  

we can talk after you present a fix

**Comment by eli-schwartz** [comment]
Autotools is a very defensible choice, particularly if a project only needs Unix support. It helps a *lot* if the project doesn't need to use libtool for great slowness (and lsof doesn't have any libraries, the one that it does use is an internal implementation detail and easily avoided).

That being said, https://sr.ht/~lattis/muon/ does exist to build meson projects without python.

**Comment by jiegec** [comment]
I have a WIP autotools-based build system rewrite in branch `autotools`.

**Comment by thesamesam** [comment]
Thanks for doing the solid work on this. It's working well for us in Gentoo and it's made things much easier and cleaner. We need a configure arg for selinux (like for rpc) but that's the only issue we've hit.

**Comment by jiegec** [comment]
> Thanks for doing the solid work on this. It's working well for us in Gentoo and it's made things much easier and cleaner. We need a configure arg for selinux (like for rpc) but that's the only issue we've hit.

Done in commit 4fbe0b78f63ce115f25cf7a49756745e3bf47fea

**Comment by thesamesam** [comment]
You're a star ❤️
