### ISSUE TITLE
[BUG] 4.99.0 - Installs liblsof.a even when --disable-static is mentioned

### ISSUE THREAD

**Issue by subnut** [lsof-org/lsof#299]
**Describe the bug**
`configure --disable-static --disable-shared` should result in neither the static nor the shared libraries to be installed. And since the libraries aren't being installed, the header files shouldn't be installed either.

Currently, it behaves as if `--disable-static` was never mentioned, i.e. installing both `liblsof.a` and the header files (`lsof.h`, `lsof_fields.h`)

**To Reproduce**
1. Download and extract https://github.com/lsof-org/lsof/releases/download/4.99.0/lsof-4.99.0.tar.gz
2. Run `configure --enable-security --disable-static --disable-shared`
3. `make`
4. `make install`

**Expected behavior**
Libraries and Header files not being installed

**Actual behaviour**
Static library is installed. Header files are installed

**Environment (please complete the following information):**

 - Kernel: Linux 6.5.11
 - OS: Void Linux
 - lsof Version: 4.99.0
 - Origin: built from release tarball

**Additional context**

**Comment by jiegec** [comment]
It seems to be a limitation of libtool. Can we workaround it?

**Comment by subnut** [comment]
I've tried my hand at a possible workaround in #300 

This is my first time interacting with autoconf/automake, so there may be mistakes..
