### ISSUE TITLE
[BUG] What happened to FreeBSD?

### ISSUE THREAD

**Issue by lrosenman** [lsof-org/lsof#302]
**Describe the bug**
Where is the FreeBSD dialect directory?  I'd like to bring it back
**To Reproduce**
cd src/freebsd

**Expected behavior**
Directory exists

**Program output**
ler in oldtbh2 in lsof/src/dialects on  master as 🧙
✔️0 ❯ ls
darwin linux

**Environment (please complete the following information):**

 - Kernel: [e.g. FreeBSD]
 - OS: [e.g. FreeBSD]
 - lsof Version: [e.g. 4.99]
 - Origin: Trying to update upstream

**Additional context**
I would have liked contact before FreeBSD was REMOVED.

**Comment by lrosenman** [comment]
N/M -- I found it in src/lib/dialects

**Comment by jiegec** [comment]
Sorry about the confusion, I moved them for liblsof.
