### ISSUE TITLE
[BUG] CI failing on Ubuntu after I released 4.99.1

### ISSUE THREAD

**Issue by lrosenman** [lsof-org/lsof#303]
**Describe the bug**
CI Failure 

https://github.com/lsof-org/lsof/actions/runs/7233444318
https://github.com/lsof-org/lsof/actions/runs/7233437774

I didn't change anything that should affect Ubuntu.

**Comment by lrosenman** [comment]
Apparently? I forgot <SOMETHING> for the release 
Can someone help me?

**Comment by lrosenman** [comment]
I fixed the version file, but it's still failing. 

I need someone on the Linux side to help.

**Comment by BenBE** [comment]
Running that test locally on HEAD (tag 4.99.2, commit fbd4650ceada0088156da5ec704f9c7db019d5fb) succeeds on Ubuntu 24.04:
```console
user@host:/home/user/dev/lsof$ bash -x ./tests/case-01-version.bash 
+ source tests/common.bash
+++ basename ./tests/case-01-version.bash .bash
++ name=case-01-version
++ '[' 0 -ne 0 ']'
++ lsof=home/user/dev/lsof/lsof
++ report=/dev/stdout
++ tcasedir=lib/dialects//tests
++ dialect=
++ sed '/VN/s/.ds VN \([0-9.a-z]*\)/\1/' ./version
+ expected_version=4.99.2
++ /home/user/dev/lsof/lsof -v
++ sed -ne 's/^ *revision: *\([0-9.a-z]*\)/\1/p'
+ actual_version=4.99.2
++ sed -ne 's/^\([0-9][0-9.a-z]*\)              .*$/\1/p' 00DIST
++ tail -1
+ dist_version=4.99.2
+ '[' 4.99.2 '!=' 4.99.2 ']'
+ '[' 4.99.2 '!=' 4.99.2 ']'
+ exit 0
```

Looking at `00DIST` I noticed some whitespace issue:
```
$ git diff
diff --git a/00DIST b/00DIST
index 624ad7a9..b3628a88 100644
--- a/00DIST
+++ b/00DIST
@@ -5577,7 +5577,7 @@ Supplement	Regenerated the 4.04 distribution to correct a non-
 		Add configure option --disable-liblsof to disable installation
 		of liblsof. (@subnut, #300)
 
-                [freebsd] fix segfault from fs info (FreeBSD bug 267760)
+		[freebsd] fix segfault from fs info (FreeBSD bug 267760)
 
 4.99.2		December  16, 2023
 
```

**Comment by lrosenman** [comment]
so it should be spaces and not tabs?

**Comment by BenBE** [comment]
Currently it is spaces, but the rest of the file is tabs …

**Comment by lrosenman** [comment]
OIC -- will fix :)

**Comment by lrosenman** [comment]
I guess it's a 3 release kind of day.

**Comment by BenBE** [comment]
As said, I could not reproduce the issue locally, but that really looks like it could be the culprit.

**Comment by lrosenman** [comment]
Well. that is NOT it 👎 

Is anyone familiar with the Linux CI/CD?

**Comment by jiegec** [comment]
Well, you have to update the version in `configure.ac`.

**Comment by lrosenman** [comment]
Is there some way to automate that to update from the version file?

**Comment by jiegec** [comment]
> Is there some way to automate that to update from the version file?

Not yet 😢

**Comment by lrosenman** [comment]
I think I missed that while I was AWOL.  Sorry for the breakage.

**Comment by lrosenman** [comment]
I think we're good now -- closing.
