### ISSUE TITLE
Missing dist tarballs for >4.99.0

### ISSUE THREAD

**Issue by thesamesam** [lsof-org/lsof#304]
The 4.99.1, 4.99.2, and 4.99.3 releases are all lacking a "distribution tarball" (produced by `make dist`) which includes pre-generated autoconf files and is guaranteed to unchange, unlike the automatic github tarballs.

Previous versions like 4.99.0 had them.

Could these be uploaded please? Thanks!

**Comment by jiegec** [comment]
Added for 4.99.3.

**Comment by thesamesam** [comment]
Thank you!!
