### ISSUE TITLE
Expressions truncated

### ISSUE THREAD

**Issue by Ricky-Tigg** [lsof-org/lsof#308]
**Describe the bug**
Hello. Despite that there is unoccupied space along the width axis, expressions whose number of characters exceed **9** and that are in the **first column** – _COMMAND_ – are truncated. Singularly, expressions that are in the **last column** – _NAME_ – are not truncated. Then as shown below, _gnome-software_ is presented as _gnome-sof_.

**Expected behavior**
Expressions not truncated.

**Program output**
```
$ lsof -i -n -P | head -2
COMMAND     PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
gnome-sof  8693  (...)   38u  IPv6  64781      0t0  TCP [2001:999:600:3941:3919:eff4:e86c:e49e]:34684->[2a04:4e42:3a::347]:443 (CLOSE_WAIT)
```
**Environment:**
 - **Linux kernel version:** 6.6.12
 - **OS:** Fedora; Desktop edition
 - **lsof version:** 4.96.3
 - **origin:** package manager
- **terminal:** gnome-terminal
- **Shell:** Bash

**Comment by jiegec** [comment]
I think this is the expected behavior. You can use `+c w` flag to change the behavior.

**Comment by jiegec** [comment]
> I can hardly imagine the typical Linux user this project had in scope at the time it developed such a uselessly complex methodology in order to define the syntaxes of commands. Happily not all projects having as target Linux users have a model such as the present one. The last suggested command is invalid; for the sake of a correct information for other readers, it is `+c 0`.

Yes, however lsof was dated back as early as 1990s, as old as Linux.
