### ISSUE TITLE
add support for FreeBSD 13 (-CURRENT, AKA HEAD) 

### ISSUE THREAD

**Issue by lrosenman** [lsof-org/lsof#49]
https://reviews.freebsd.org/D20341

Can someone add this change to a release?

Thanks! (also see the comment).

**Comment by lrosenman** [comment]
I'm at a conference, so do not have my repo available for a PR.

**Comment by masatake** [comment]
You don't have to be hurry up. You can make a pull request after getting the access to your repo.
Please, don't forget updating 00DIST and 00CREDIT.

**Comment by lrosenman** [comment]
PR https://github.com/lsof-org/lsof/pull/51 opened for this

**Comment by lrosenman** [comment]
What do we, as a project, want to do about cleaning up EOL FreeBSD releases?

**Comment by masatake** [comment]
(I have no idea about EOL FreeBSD releases.)

**Comment by lrosenman** [comment]
Vic would keep ancient/old/EOL releases buildable in the source releases.  My colleagues on the FreeBSD project would like to start simplifying this to only support current NON-EOL FreeBSD releases, which means no longer supporting anything prior to 11.2. 

If the project wants to go that way, I can start making that happen.

**Comment by lrosenman** [comment]
@masatake should I assume we have carte blanche within the FreeBSD dialect as to what versions we support?  Or do we want to have a project-wide policy?

**Comment by masatake** [comment]
No. We don't have.
If you are not here, I will support only versions that are tested on cirrus-ci.
However, you are here. So you can do as you want.

**Comment by lrosenman** [comment]
Ok, I will make PR's to simplify this in the next days/weeks. I'm going to close this issue as the original issue here was handled.
