### ISSUE TITLE
Allow to pass multipe pids to -p option 

### ISSUE THREAD

**Issue by masatake** [lsof-org/lsof#5]
Accept following command line will be useful.

```
   lsof -p $(pidof httpd)
```

**Comment by hardikpnsp** [comment]
@masatake, seems like `lsof` already supports a comma-separated list of process IDs, and `pidof` has the option to set a separator with `-d` option. 

#### Example:
```bash
pidof spotify
>>14242 14222 14209 14202

pidof spotify -d ,
>>14242,14222,14209,14202
```

Thus you can do
```bash
lsof -p $(pidof httpd -d ,)
``` 
and it should work as expected.

**Comment by masatake** [comment]
I agree. 

You man use Debian (or Ubuntu).  If you use Fedora/RHEL/CentOS, you must specify -S instead of -d.
https://gitlab.com/procps-ng/procps/-/commit/73492b182dc60c1605d1b0d62de651fad97807af
