### ISSUE TITLE
run test cases for FreeBSD 13 on cirrus-ci

### ISSUE THREAD

**Issue by masatake** [lsof-org/lsof#50]
See .cirrus.yml.
As far as I tried, freebsd-13-0-current-amd64-v20190503 never booted well.

**Comment by lrosenman** [comment]
How can I get access to cirrus to change/look around?  Also, in the  .cirrus.yml, why do you install gcc?

**Comment by masatake** [comment]
> @masatake How can I get access to cirrus to change/look around

See https://cirrus-ci.org/ and https://cirrus-ci.org/guide/FreeBSD/ .

> Also, in the .cirrus.yml, why do you install gcc?

I don't have enough knowledge of FreeBSD. My knowledge is very limited to GNU/Linux.
If you find a questionable in what I did, please fix it.

However, allow me to use bash to write the test harness and test cases.

**Comment by lrosenman** [comment]
I've updated the .cirrus.yml file in my branch, and have a question out to the Cirrus folks on how to debug the fact that it's not starting the image.

**Comment by lrosenman** [comment]
I got an answer back from Cirrus:

> It seems FreeBSD 13 VM never executes startup script which is used by Cirrus CI to start a task. You can try it yourself on GCP:
> 
> gcloud compute instances create instance-1 --zone=us-central1-a --machine-type=n1-standard-2 --metadata=startup-script=echo\ \"Hello\" --image=freebsd-13-0-current-amd64-v20190517 --image-project=freebsd-org-cloud-dev
> 
> You can check console output of the VM
> 
I'll follow-up within the FreeBSD project to fix the image(s).

**Comment by masatake** [comment]
Nice!

**Comment by lrosenman** [comment]
I tried to launch a FreeBSD-13 GCE Instance using Fedor's (from Cirrus-CI) instructions, and found:

freebsd-update 680 - - Firstboot freebsd-update disabled on 13.0-CURRENT
/etc/rc: WARNING: run_rc_command: cannot run /usr/local/bin/google_instance_setup
Starting google_network_daemon.
daemon: /usr/local/bin/google_network_daemon: No such file or directory
Starting google_accounts_daemon.
daemon: /usr/local/bin/google_accounts_daemon: No such file or directory
Starting google_clock_skew_daemon.
daemon: /usr/local/bin/google_clock_skew_daemon: No such file or directory
eval: /usr/local/bin/google_metadata_script_runner: not found
Starting sendmail_submit.
Starting sendmail_msp_queue.
Configuring vt: blanktime.
Generating RSA host key.
2048 SHA256:dqwjbK99g11yOSnaA2gvvn2QJk8LJuDjMC1Xez065PE root@instance-1 (RSA)
Generating ECDSA host key.
256 SHA256:EJoxsw7ekTF/8eY3Ky2fWeIS316tmMVKLVZ9KFnHO1Q root@instance-1 (ECDSA)
Generating ED25519 host key.
256 SHA256:mW93NTPk4tyMFZuuTeUH5twO1newTKpthQ38uAMBiSE root@instance-1 (ED25519)
Performing sanity check on sshd configuration.
Starting sshd.
Starting cron.
Autoloading module: intpm.ko
Starting background file system checks in 60 seconds.


None of the GCE magic processes run.  I've sent mail to the person Glen Barber (RE Team for FreeBSD) suggested, and am awaiting a reply.

**Comment by lrosenman** [comment]
Working with Glen, we've got a fix in the FreeBSD tree for this.  The next set of images on GCE should work.  I'll verify tomorrow or Saturday when they are available.

**Comment by lrosenman** [comment]
This is the fixing commit, and new builds start at 00:00 UTC tonight (07:00 PM US/CDT).
https://svnweb.freebsd.org/changeset/base/348438

**Comment by masatake** [comment]
Excellent!

**Comment by lrosenman** [comment]
That did _NOT_ fix it.  Glen is working out what all needs to be done.  I'll keep on it.

**Comment by scott4long** [comment]
What’s the easiest way to test a GCM instance on my own?  I have some free time to look at this.

Scott

**Comment by lrosenman** [comment]
Fedor of CirrusCI gave me the following command-line, but the problem I have is when launched NO login works.

```gcloud compute instances create instance-1 --zone=us-central1-a --machine-type=n1-standard-2 --metadata=startup-script=echo\ \"Hello\" --image=freebsd-12-0-stable-amd64-v20190531 --image-project=freebsd-org-cloud-dev```

I've tried both the 12-0 and 13-0 images from today.

 > gcloud compute images list --project freebsd-org-cloud-dev --no-standard-images

will give a list of all our (FreeBSD) images.

**Comment by lrosenman** [comment]
I can also send you what I see in the console via private mail if you'd like (I've been corresponding with gjb@FreeBSD.org on this. 

Thanks for any help, @scott4long

**Comment by lrosenman** [comment]
Actually, with some help from swills@FreeBSD.org via IRC, we determined that my issue with today's images was because oslogin isn't working.  That's not germane to the cirrus-ci issue.  I'm going to try and generate a PR to update the yml file to use today's 13-current image and see if cirrus likes it.

**Comment by lrosenman** [comment]
see https://github.com/lsof-org/lsof/pull/55 it now actually runs but the test suite doesn't like it.

**Comment by masatake** [comment]
@scott4long, thank you very much.

**Comment by masatake** [comment]
Fixed in #55 and #56.
Thank you, everyone!
