### ISSUE TITLE
Clarify if this is the official lsof now, or a fork

### ISSUE THREAD

**Issue by RalphCorderoy** [lsof-org/lsof#53]
Add a prominent explanation, i.e. in README.md, as to how this repo came about.

- What version of the original lsof did it start with?
- Is this now the official lsof, long maintained by Victor Abell, or a fork.
- Has Victor given his blessing.

Linux distributions are looking for lsof updates and are puzzled if this is the new upstream source they should use.

**Comment by masatake** [comment]
If inspecting our soruce tree carefully, you can know this is the official fork.
I'm bad in English. So I don't want to take more time for the explanation.
So a pull request is welcome.

Seeing the situation where lsof development is, whether official or not is not so important.
Instead, how active the project is is more important to extend the life of lsof.
Linux distributions should choose the most active project as upstream project.
If GNU/Linux distributions consider this project is not so active, they should not choose this project as upstream.
