### ISSUE TITLE
Define the criteria for making a new release?

### ISSUE THREAD

**Issue by lrosenman** [lsof-org/lsof#54]
What are our criteria for pushing a new release from Master?

**Comment by masatake** [comment]
When one us us thinks ready to release.
#48 requires Linux 5.2 which is not released yet.
So, I think we should make a new release.

**Comment by masatake** [comment]
How about FreeBSD side?

**Comment by lrosenman** [comment]
I have the equivalent of #52 patched into the port, but a release would be nice.

**Comment by masatake** [comment]
> I have the equivalent of #52 patched into the port, but a release would be nice.
I see. However, I'm in busy for awhile.

If your next patch is merged, we would like to make a release.
In that timing, I will try to tell you the operation to make a release at github.
So both us can make a release. It is important to extend the life of lsof:-)

**Comment by lrosenman** [comment]
Ok.  I intend to work on cleaning out the EOL releases of FreeBSD from the freebsd specific files when I get home from this conference.

**Comment by masatake** [comment]
As we make release-tarballs per dialect, so we don't need serious consensus about the timing of release between us.
See #96.
