### ISSUE TITLE
Show deleted files

### ISSUE THREAD

**Issue by kaplinale** [lsof-org/lsof#65]
Sometimes we need to troubleshoot some problems related with diskspace on filesystem. And sometimes it happens that we can not find the file or resource that fills this disk space. There is a way when big file already physically deleted from filesystem. But some process continues to write into file. I would like suggest to include a simple shell script into this package that will find and show that files. For example this script:
https://github.com/kaplinale/lsdf

Thank you!

**Comment by masatake** [comment]
Thank you.
We have to clear two things before adding new code.

* Whether this feature is linux specific or not.
* Which field we should use to store "deleted" information.

**Comment by kaplinale** [comment]
I think this feature is absolutely linux specific because it use an information stored in /proc filesystem.

**Comment by masatake** [comment]
You are talking about the way to implementation. On linux, we will get information from /proc.
However, even on the other OS, it may be possible that a process has a fd whose backing store file is removed from a file system. So, I think the feature is not linux specific. Of coruse, there is a case that the feature can be implemented only for linux.

**Comment by masatake** [comment]
I must study both how lsof manages fields and the kAPI of FreeBSD.

**Comment by masatake** [comment]
In dproc.c:
```
	     * If the file has been deleted, reset its type to "DEL";
	     * otherwise generate a stat() error name addition.
```
It menas what we need is already implemented.
See man lsof:
```
                 or ``DEL'' for a Linux map file that has been deleted;
```

The command line we need is listing all "DEL" type fds.

**Comment by masatake** [comment]
I cannot find any option for filtering.
So what we can do now is:
```
lsof | grep '\<DEL\>'
```
like
```
[yamato@slave ctags-github]$ sudo lsof | grep '\<DEL\>'
sudo lsof | grep '\<DEL\>'
lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1000/gvfs
      Output information may be incomplete.
systemd-u   943          root  DEL       REG              253,2                 2383384 /var/lib/sss/mc/group
avahi-dae  1295         avahi  DEL       REG              253,2                 2383824 /var/lib/sss/mc/initgroups
sssd       1317          root  DEL       REG              253,2                 2383824 /var/lib/sss/mc/initgroups
ava
...

**Comment by masatake** [comment]
DEL is printed at FD field though the man page explains DEL as the value of TYPE field.
This looks a bug. However, if we fix it, we may break compatibilities.

**Comment by masatake** [comment]
Rather I should recognize this is a bug of man page, not of code.

**Comment by kaplinale** [comment]
Okay. I found this info in documentation:

a.  Finding an Unlinked Open File
  =================================

  A pesky variant of a file that is filling a file system is an
  unlinked file to which some process is still writing.  When a
  process opens a file and then unlinks it, the file's resources
  remain in use by the process, but the file's directory entries
  are removed.  Hence, even when you know the directory where the
  file once resided, you can't detect it with ls.

  This can be an administrative problem when the unlinked file is
  large, and the process that holds it open continues to write to
  it.  Only when the process closes the file will its resources,
  particularly disk space, be released.

  Lsof can help you find unlinked files on local disks.  It has an
  option, +L, that will list the link counts of open files.  That
  helps because an unlinked file on a local disk has a zero link
  count.  Note: this is NOT true for NFS files, accessed from a
  remote server.

  You could use the option to list all files and look for a zero
  link count in the NLINK column -- e.g.,

    $lsof +L
    COMMAND   PID USER   FD  TYPE DEVICE SIZE/OFF NLINK  NODE NAME
    ...
    less    25366  abe  txt  VREG    6,0    40960     1 76319 /usr/...
    ...
  > less    25366  abe    3r VREG    6,0    17360     0 98768 / (/dev/sd0a)

  Better yet, you can specify an upper bound to the +L option, and
  lsof will select only files that have a link count less than the
  upper bound.  For example:

    $ lsof +L1
    COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NLINK  NODE NAME
    less    25366  abe    3r  VREG    6,0    17360     0 98768 / (/dev/sd0a)

  You can use lsof's -a (AND) option to narrow the link count search
  to a particular file system.  For example, to look for zero link
  counts on the /home file system, use:

    $ lsof -a +L1 /home

But I don't understood why I'm getting so big  difference between lsof's output(for eg. lsof -a +L1) and output of my script which parse every PID stored in procfs.

**Comment by masatake** [comment]
How about 
```
lsof -K -a +L1
```
?

**Comment by kaplinale** [comment]
Thank you! Seems I figured out in this question.

**Comment by masatake** [comment]
So, I think we can close this issue. Do I misunderstand the original request?

**Comment by kaplinale** [comment]
Yes, Let's close it.
