### ISSUE TITLE
man page is not built for Linux dialect and does not work on its own

### ISSUE THREAD

**Issue by greenius** [lsof-org/lsof#66]
Some of the dialects (osr and n+obsd)  have a rule to convert Lsof.8 into lsof.0 

However the linux dialect Makefile has no rules for making the man page file.

The first line of Lsof.8 is 
`.so ./version`

which includes source from the file "version" in the source code folder.  This does not work if simply copied to somewhere like /usr/share/man/man8 which does not contain the file "./version"

**Comment by greenius** [comment]
There is also another source include
`.so ./00DIALECTS`

**Comment by masatake** [comment]
It seems that support/makeman handle this.

**Comment by subnut** [comment]
@greenius `soelim` executable from the `groff` package can also be used

**Comment by jiegec** [comment]
The correct way is to use `soelim` as suggested by @subnut .
