### ISSUE TITLE
Configure generates invalid Makefile on macOS (darwin)

### ISSUE THREAD

**Issue by alebcay** [lsof-org/lsof#68]
Running the build process on macOS Mojave (darwin 18.6.0)

```
==> ./Configure -n darwin
Unknown Darwin release: 18.6.0
Assuming Darwin 12.0
Configuring libproc-based Darwin lsof
rm -f ddev.c dfile.c dlsof.h dmnt.c dnode*.c dproc.c dproto.h dsock.c dstore.c dzfs.h kernelbase.h machine.h machine.h.old new_machine.h __lseek.s Makefile Makefile.zfs ./tests/config.cflags
rm -f ./tests/config.cc ./tests/config.xobj ./tests/config.ldflags
Testing C library for localtime() and strftime(), using cc ... present
ln -s dialects/darwin/libproc/dlsof.h dlsof.h
ln -s dialects/darwin/libproc/ddev.c ddev.c
ln -s dialects/darwin/libproc/dfile.c dfile.c
ln -s dialects/darwin/libproc/dmnt.c dmnt.c
ln -s dialects/darwin/libproc/dproc.c dproc.c
ln -s dialects/darwin/libproc/dproto.h dproto.h
ln -s dialects/darwin/libproc/dsock.c dsock.c
ln -s dialects/darwin/libproc/dstore.c dstore.c
ln -s dialects/darwin/libproc/machine.h machine.h
Makefile and lib/Makefile created.
./tests/config.cc created
./tests/config.cflags created
./tests/config.ldflags created
./tests/config.xobj created
==> make
Makefile:6: *** missing separator.  Stop.
```

The error that is reported is here, in the generated Makefile:
```
# darwin Makefile for lsof revision 4.93.2

CC=     cc

CCV=    10.0.1 (clang-1001.0.46.4)
9.0

LIB=    lib/liblsof.a

CINFO=  libproc-based

[...]
```

The problem is that "9.0" (line 6) right after `CCV`, it shouldn't be there and I'm not sure how it gets there. Removing this line from `Makefile` and `lib/Makefile` fixes the build.

**Comment by masatake** [comment]
Could you make a pull request representing your suggestion?

**Comment by alebcay** [comment]
I would, but to be honest, I'm not exactly sure what to change to make the issue go away. All I know is that the part excerpted above
```
CCV=    10.0.1 (clang-1001.0.46.4)
9.0
```
should be
```
CCV=    10.0.1 (clang-1001.0.46.4)
```

I have no idea where the `9.0` is coming from.

**Comment by masatake** [comment]
None knows it :-P
Please, write what you wrote here to your commit log.

**Comment by alebcay** [comment]
Got around this issue by just setting `LSOF_CC` and `LSOF_CCV`. `Configure` remains broken on macOS.

**Comment by masatake** [comment]
I may misunderstand what you wrote. It seems that you don't know how to fix the root cause.

**Comment by alebcay** [comment]
Correct, I don't know how to fix the root cause. I don't know why the script is broken; I just found a workaround.

**Comment by masatake** [comment]
I would like to see the output of `cc -v 2>&1` on the platform you use.

I found following code in Configure:

```
  darwin)
    if test "X$LSOF_CC" = "X"	# {
    then
      LSOF_CC=cc
      LSOF_CCV=`$LSOF_CC -v 2>&1 | sed -n 's/.*version \(.*\)/\1/p'`
    fi	# }
```
```
if test "X$LSOF_CCV" != "X"	# {
then
  echo "" >> $LSOF_MKFC
  echo "CCV=	$LSOF_CCV" >> $LSOF_MKFC
fi	# }
```

I guess the "9.0" may come from 
```
`$LSOF_CC -v 2>&1 | sed -n 's/.*version \(.*\)/\1/p'`
```
.

**Comment by alebcay** [comment]
```
• cc -v 2>&1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
Found CUDA installation: /usr/local/cuda, version 9.0
```

```
• cc -v 2>&1 | sed -n 's/.*version \(.*\)/\1/p'
10.0.1 (clang-1001.0.46.4)
9.0
```

Looks like your guess is correct, it's picking up on the CUDA installation version number as well.

**Comment by masatake** [comment]
So I wonder how we can fix this issue.
```
LSOF_CCV=`$LSOF_CC -v 2>&1 | grep -v CUDA | sed -n 's/.*version \(.*\)/\1/p'`
```
is the way I found.
Do you have any better idea?

**Comment by alebcay** [comment]
That line works for me; I think it will work pretty well. If we want to be more specific, we can chain in `grep "Apple LLVM"` before the `sed` to make sure that it gets only the `clang` version.

**Comment by masatake** [comment]
I see.
I will wait for a pull request from you.

----

As I wrote in README.md, this project doesn't support darwin because none in the project knows about it. However, we will merge changes for the platform.

**Comment by alebcay** [comment]
Thanks, I appreciate it.
