### ISSUE TITLE
Provide an API

### ISSUE THREAD

**Issue by Logout22** [lsof-org/lsof#79]
lsof right now cannot be used in scripts without parsing its output. It would be good to have a liblsof available for C programmers. It should have an interface similar to this Perl frontend: https://metacpan.org/pod/Unix::Lsof

I think field output needs to be separated from field generation for that. Is there already some sort of interface within lsof that is not exposed? I saw that in the documentation that the tests also parse the lsof output, and also they themselves cannot very easily be automated.

**Comment by masatake** [comment]
Did you read "OUTPUT FOR OTHER PROGRAMS" section of man page (lsof(1))?
If you build lsof executable from git repo, you will also find lib/liblsof.a.
As far as I know these two can be start points.

**Comment by Logout22** [comment]
Thanks for the quick response @masatake , these are generally good pointers for a beginner. Right now, you can write:

    #include <stdio.h>
    #include <string.h>
    
    int main() {
        int length = 1280;
        char buffer[length];
        memset(buffer, 0, length);
        char* end = buffer + length - 1;
        char* current = buffer;
    
        FILE* pipe = popen("lsof -F p", "r");
        if (!pipe) return 1;
        do {
            size_t bytes_read = fread(current, 1, end - current, pipe);
            if (bytes_read == 0) break;
            current += bytes_read;
        } while (current != end);
        pclose(pipe);
    
        // iterate over lines in buffer
    }

This certainly works, but is very complicated and error-prone, especially because I have to start the lsof application, and because I need to parse the output again instead of receiving a data structure. I want to have something like this:

    #include <lsof_api.h>
    
    int main() {
        LSOF_ENTRY* entries;
        int no_of_entries = lsof(&entries);
        if (no_of_entries) {
            return 1;
        }
        for (int i = 0; i < no_of_entries; i++) {
            int pid = entries[i].pid;
            // process PID
        }
        lsof_free(entries);
    }

As you can see this would be way easier to use and involve far less glue code, even in such a simple example.

liblsof.a is only internal from what I can see. Even if it is thought to be compiled into other programs, it does not have a good user interface like I sketched above.

**Comment by masatake** [comment]
How strongly do you want the API? Or showing just an idea?

I agree with you that it is better to have. However, I don't need it tomorrow.
So I will not work on it. I do programming only in shell. 
So the API is not needed. Just command output is enough for me.

If you are thinking about hacking lsof for adding API by yourself, tell me.
I don't know well about lsof, but I will try to help you. However, I promise you there is no easy way.
The difficulties come from two factors.
The first one is that lsof supports multiple platform. See #70 as an example of difficulties. Designing unified API for such software requires the designer has deep and wide knowledges. 
The second one is that lsof is rather old software.  What I mean can know by reading the source code of lsof.

**Comment by masatake** [comment]
I myself cannot find time for working this topic.

**Comment by Logout22** [comment]
Sorry for not responding. I thought your comment was very conclusive and I did not feel the need to add anything to it. You have a point and after having a look at the lsof code myself, I totally agree that reworking lsof into a library interface would not pay off in the long term and is probably not worth the effort. So closing the issue is fine by me.
