### ISSUE TITLE
lsof prints usage on missing files

### ISSUE THREAD

**Issue by rowlap** [lsof-org/lsof#90]
```
## file not in use
$ lsof /bin/ls

## file not in use + non-existent
$ lsof /bin/ls /bin/lsxxx
lsof: status error on /bin/lsxxx: No such file or directory

## only non-existent
$ lsof /bin/lsxxx
lsof: status error on /bin/lsxxx: No such file or directory
lsof 4.91
 latest revision: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/
 latest FAQ: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/FAQ
 latest man page: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/lsof_man
 usage: [-?abhKlnNoOPRtUvVX] [+|-c c] [+|-d s] [+D D] [+|-E] [+|-e s] [+|-f[gG]]
 [-F [f]] [-g [s]] [-i [i]] [+|-L [l]] [+m [m]] [+|-M] [-o [o]] [-p s]
 [+|-r [t]] [-s [p:s]] [-S [t]] [-T [t]] [-u s] [+|-w] [-x [fl]] [--] [names]
Use the ``-h'' option to get more help information.
```

Is this intentional? It seems inconsistent to print usage for missing files *unless* extant files are also specified.

**Comment by masatake** [comment]
I agree with your pointing out.

**Comment by masatake** [comment]
I inspected the code.
```
	if (!ss)
	    err = 1;
	return((int)err);
```

main() calls ck_file_arg().
ck_file_arg() checks the existance of files passed from command line.

ck_file_arg checks the existence of files one by one.
ss is the variable where how many files exist.
If the function detects all the files passed from the command line don't exist (the case ss is 0), the function returns 1. if the function detects at least one file exists (the case ss is greater than 0), the function return 0.

The main function prints the usage only when ck_file_arg returns 1.
lsof runs when one of the files passed from command line exits even if the rest of the files in the command line doesn't exist. For the non-existing files, lsof prints short warning.

lsof stops self and prints usage all of the files passed from the command line don't exist.

Though I agreed with you in the last comment. However, I would like to withdraw the comment.
This behavior is consistent well, and we should not change it.

**Comment by rowlap** [comment]
When usage is displayed, the implication to the user is that an syntax error has been made. When calling out to lsof from other programs, I really would prefer that lsof stderr output doesn't depend on ephemeral conditions such as file existence.

Are there other cli utilities which respond to missing files in this way?

**Comment by masatake** [comment]
I agree. Could you try #90?
(And I would like you to review the change for 00DIST in the pull request.)
